//
//  SQLPredicateTranslatorOptions.swift
//  DataStoreKit
//
//  Copyright 2025 Asymbas and Anferne Pineda.
//  Licensed under the Apache License, Version 2.0 (see LICENSE file).
//  SPDX-License-Identifier: Apache-2.0
//

public struct SQLPredicateTranslatorOptions: OptionSet, Sendable {
    nonisolated private static let allowedMask: Int = (1 << 11) - 1 // bits 0...10
    nonisolated public let rawValue: Int
    
    nonisolated public init(rawValue: Int) {
        precondition(
            ~Self.allowedMask & rawValue == 0,
             "Invalid SQLPredicateTranslatorOptions: \(rawValue)"
        )
        self.init(uncheckedRawValue: rawValue)
    }
    
    nonisolated private init(uncheckedRawValue: Int) {
        self.rawValue = uncheckedRawValue
    }
}

public extension SQLPredicateTranslatorOptions {
    /// Produces more detailed descriptions for fragments.
    nonisolated static var useDetailedLogging: Self {
        .init(uncheckedRawValue: 1 << 0)
    }
    /// Increased logging for predicate expressions.
    nonisolated static var useVerboseLogging: Self {
        .init(uncheckedRawValue: 1 << 1)
    }
    /// Overrides all logging-related options and will log unfiltered.
    nonisolated static var logAllPredicateExpressions: Self {
        .init(uncheckedRawValue: 1 << 2)
    }
    /// Prints the logs without having to update loggers to use `trace`.
    nonisolated static var preferStandardOutput: Self {
        .init(uncheckedRawValue: 1 << 3)
    }
    /// Print SQL statement without aliasing.
    nonisolated static var generateSQLStatement: Self {
        .init(uncheckedRawValue: 1 << 4)
    }
    /// Enables `EXPLAIN QUERY PLAN`.
    nonisolated static var explainQueryPlan: Self {
        .init(uncheckedRawValue: 1 << 5)
    }
    /// Allows a translation to be hashed.
    nonisolated static var isCachingPredicates: Self {
        .init(uncheckedRawValue: 1 << 6)
    }
    /// Allows lookup and binding on a key path not generated by the model macro.
    nonisolated static var allowKeyPathVariantsForPropertyLookup: Self {
        .init(uncheckedRawValue: 1 << 7)
    }
    /// Prevents additional key path resolutions when the match fails.
    nonisolated static var disableKeyPathPropertyLookupFallbacks: Self {
        .init(uncheckedRawValue: 1 << 8)
    }
    /// Determines whether the SQL should also check the JSON's path.
    nonisolated static var useFallbackOnCompositeAttributes: Self {
        .init(uncheckedRawValue: 1 << 9)
    }
    /// Appends comments to SQL to show where the fragment is being generated.
    nonisolated static var shouldMarkStartOfPredicateExpression: Self {
        .init(uncheckedRawValue: 1 << 10)
    }
}
