//
//  MirrorSchemaPropertyMetadata.swift
//  DataStoreKit
//
//  Copyright 2025 Asymbas and Anferne Pineda.
//  Licensed under the Apache License, Version 2.0 (see LICENSE file).
//  SPDX-License-Identifier: Apache-2.0
//

import DataStoreSupport
import Logging
import SwiftData

nonisolated private let logger: Logger = .init(label: "com.asymbas.datastorekit.bootstrap")

/// Uses `Mirror` to extract property metadata from `PersistentModel.schemaMetadata`.
///
/// `PersistentModel` types annotated with the `@Model` macro generates its results into a static property.
///
/// - Note:
///   - The metadata is not the same instance provided in schema.
///   - Inherited properties are excluded.
/// - Parameters:
///   - type:
///     The model type that conforms to `PersistentModel`.
///   - onPropertyMetadata:
///     A closure that provides a handler for the property macro values.
///     The properties return in the order they were written.
///     - `name`: The property name as written in the Swift file.
///     - `keyPath`: The key path for this stored property.
///     - `defaultValue`: The inline value that was assigned to the property.
///     - `metadata`: A `SchemaProperty` generated by a macro.
///       - `@Attribute` will produce a `Schema.Attribute` metadata.
///       - `@Relationship` will produce a `Schema.Relationship` metadata.
///       - `nil` when a stored property is not annotated with a macro.
///   - onAuxiliaryMetadata:
///     A closure that provides a handler for auxiliary macro values.
///     Their key paths point to `\Schema.encodingVersion` and has no default values.
///     Both can only occur zero or once.
///     - `name`: The name is `SwiftData.Schema.<SchemaProperty>`.
///     - `metadata`:
///       - `#Index` generates a `Schema.Index` metadata.
///       - `#Unique` generates a `Schema.Unique` metadata.
/// - Throws:
///   Rethrows an error from either closure.
nonisolated public func reflectSchemaMetadata<Model>(
    for type: Model.Type,
    onPropertyMetadata: (
        _ index: Int,
        _ name: String,
        _ keyPath: (PartialKeyPath<Model> & Sendable),
        _ defaultValue: Any?,
        _ metadata: (any SchemaProperty)?
    ) throws -> Void,
    onAuxiliaryMetadata: ((
        _ name: String,
        _ metadata: any SchemaProperty
    ) throws -> Void)? = nil
) rethrows where Model: PersistentModel & SendableMetatype {
    var entityName = String(reflecting: Model.self)
    entityName = entityName.split(separator: ".").dropFirst().joined(separator: "_")
    for (index, property) in type.schemaMetadata.enumerated() {
        var nameValue: String?
        var keyPathValue: (PartialKeyPath<Model> & Sendable)?
        var defaultValue: Any?
        var metadataValue: (any SchemaProperty)?
        for child in Mirror(reflecting: property).children {
            switch child.label {
            case "name": nameValue = child.value as? String
            case "keypath": keyPathValue = sendable(cast: child.value)
            case "defaultValue": defaultValue = child.value
            case "metadata": metadataValue = child.value as? any SchemaProperty
            default: assertionFailure("Unexpected child label: \(child.label ?? "nil")")
            }
            logger.trace(
                """
                Reflecting: \(entityName).\(nameValue ?? "nil")
                Schema.PropertyMetadata.\(child.label ?? "nil"): \(child.value)
                """
            )
        }
        // Skip `Schema.Index` and `Schema.Unique`.
        // Both have `\Schema.encodingVersion` as key path placeholders and is a type mismatch.
        if nameValue == "SwiftData.Schema.Index" || nameValue == "SwiftData.Schema.Unique" {
            guard let metadataValue else {
                preconditionFailure("SchemaProperty should have been present.")
            }
            try onAuxiliaryMetadata?((nameValue ?? "nil"), metadataValue)
            continue
        }
        guard let nameValue else {
            preconditionFailure("Unable to extract name required for PropertyMetadata: \(type)")
        }
        guard let keyPathValue else {
            preconditionFailure("Unable to extract key path required for PropertyMetadata: \(type)")
        }
        try onPropertyMetadata(index, nameValue, keyPathValue, defaultValue, metadataValue)
    }
}

nonisolated public func reflectPropertyMetadata<T>(for type: T.Type) -> [PropertyMetadata]
where T: PersistentModel & SendableMetatype {
    var properties = [PropertyMetadata]()
    reflectSchemaMetadata(for: type) { index, name, keyPath, defaultValue, metadata in
        properties.append(.init(
            index: index,
            name: name,
            keyPath: keyPath,
            defaultValue: defaultValue,
            metadata: metadata ?? Schema.Attribute(name: "", valueType: T.self)
        ))
    }
    logger.trace("Reflection result for \(type) property metadata: \(properties)")
    return properties
}
